### ISSUE TITLE
Not able to run celery

### ISSUE THREAD

**Issue by findsarfaraz** [antoinemartin/django-windows-tools#11]
Here is my service.ini.
https://dpaste.de/idm5

The service shows running. But nothing happens. Also, is it not celerybeat deprecated and should be replaced with celery beat command. 

I am confused about where to get celerybeat.pid file in log folder as well. All tutorial gives same example which is not working. I am using windows 7 64 bit and celery 3.1.17

Thanks

**Comment by bernardotorres** [comment]
Could you please paste your service.ini again?

I am having problem running services as well.

**Comment by mrbean-bremen** [comment]
@findsarfaraz - is this still an issue? Without more information there is nothing we can do about this (trying to cleanup issues...)

**Comment by mrbean-bremen** [comment]
Closing this, as not enough information is provided, and OP has not responded.
