### ISSUE TITLE
CommandError: The FastCGI application creation has failed

### ISSUE THREAD

**Issue by Moataz-E** [antoinemartin/django-windows-tools#15]
Hi,

I am trying to deploy my django application on windows but I am currently running into an issue when I run this command in an admin-privilaged windows powershell:

> C:\Python27\python.exe "C:\<location of project>\manage.py" winfcgi_install --binding="http://localhost:8080"

> ERROR ( message:New application object missing required attributes. Cannot add duplicate collection entry of type 'application' with combined key attributes 'fullPath, arguments' respectively set to 'C:\Python27\python.exe, C:\<location of project>\manage.py winfcgi --pythonpath=C:\<location of project>'. )

Can anyone provide help with what might be causing this issue?

**Comment by mrbean-bremen** [comment]
Try to add a site name for your website (--site-name=<sitename>), maybe this is causing the problem.

**Comment by Moataz-E** [comment]
Hi,

I am still getting the same issue. The following is the generated web.config before the program crashes:

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <handlers>
	  <clear/>
      <add name="FastCGI" path="*" verb="*" modules="FastCgiModule" scriptProcessor="C:\Python27\python.exe|C:<location of project>\manage.py winfcgi --pythonpath=C:\<location of project>" resourceType="Unspecified" requireAccess="Script" />
    </handlers>
  </system.webServer>
</configuration>`

**Comment by Moataz-E** [comment]
Also, when I add the --skip-fastcgi option to skip that point of failure, I get the following error:

`ERROR ( message:Failed to add duplicate collection element`

Seems like it is similar to the duplicate error mentioned earlier, where could these duplicates possibly be?

**Comment by mrbean-bremen** [comment]
It looks like the site already exists - but I guess you checked that already. Can you check if anything has been added at all in IIS?

**Comment by Moataz-E** [comment]
Actually, I found what the issue is. It turns out there is an Application Pools in IIS Manager which already contained records for what I was trying to create, and delete didn't correctly dispose of these records.

**Comment by mrbean-bremen** [comment]
Ok, good to hear. Can we close this issue, then?

**Comment by Moataz-E** [comment]
Issue closed, thanks a lot!

**Comment by lewisMachilika** [comment]
yes issue closed
