### ISSUE TITLE
winservice_install keeps throwing error: KeyError: 'service_name'

### ISSUE THREAD

**Issue by cdrandin** [antoinemartin/django-windows-tools#20]
I was previously able to get `python manage.py winservice_install` working fine, but I was previously encountering an error with the services not starting up.

I came across [this](https://github.com/antoinemartin/django-windows-tools/issues/7). In hopes of resolving the issue, so figured getting the most recent dev version would maybe fix things by pip install through git.

This ended up breaking it much more. I am not even sure where I should even get the value from. I have tried passing as an argument `--service_name`, but winservice_install didn't like it. I tried `python manage.py help winservice_install`, but didn't provide any insight on passing that specific or any type of relevant argument.

**Comment by mrbean-bremen** [comment]
Can you say what has changed? Django version, Python version, and/or django-windows-tools version? 
Note also that the most recent dev version is the same as the pypi version 0.2 - nothing has changed since that release.

**Comment by cdrandin** [comment]
Uh.if the dev is the same as what's on pypi then literally nothing changed. 

Using python 2.7. Django 1.7. django-windows-tools 0.2.

All I did was install through pip via git 

'pip install -e git...#egg=django-windows-tools '

Which preceded to upgrade other packages.

**Comment by mrbean-bremen** [comment]
Try using an earlier version from pypi then - the latest changes have been for Python 3 and Django 1.11 support, maybe it broke something for django 1.7 - try version 0.1.3

**Comment by cdrandin** [comment]
Reverting back to version 0.1.3 resulted in the package working again.
