### ISSUE TITLE
CommandError: It seems that The CGI module is not installed

### ISSUE THREAD

**Issue by honi** [antoinemartin/django-windows-tools#3]
I have enabled CGI support following these instructions: http://www.iis.net/configreference/system.webserver/cgi

Running on Windows 7 Ultimate 64bits.

When running winfcgi_install command I get the error:
CommandError: It seems that The CGI module is not installed

Not sure how to fix this, as the CGI module is actually installed, I can see it in the IIS Manager.

**Comment by mrbean-bremen** [comment]
Closing this after enhancing the error message as proposed.
