### ISSUE TITLE
The Celeryd can not launch properly, it dies! 

### ISSUE THREAD

**Issue by timtan** [antoinemartin/django-windows-tools#7]
Celeryd dies in a very fast fashion.  but celerybeat works correctly. 

Error Message as I executed  the command:

   python service.py debug

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\billiard\forking.py", line 503, in main
    prepare(preparation_data)
  File "C:\Python27\lib\site-packages\billiard\forking.py", line 644, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named PythonService
# my service.ini

[services]

run=celeryd

clean=c:\logs\celeryd.pid;c:\logs\celerybeat.pid

[celeryd]

command=celeryd

parameters=-f c:\logs\celery.log -l debug --settings=rcs_main.win_dev 

[celerybeat]

command=celerybeat

parameters=-f c:\logs\beat.log -l info --pidfile=c:\logs\celerybeat.pid --settings=rcs_main.win_dev

[runserver]

command=runserver

parameters=--noreload --insecure 0.0.0.0:8000

[log]

filename=c:\logs\service.log

level=INFO
## 

Here is my log

[INFO/Process-1] Starting command : C:\Python27\lib\site-packages\django_windows_tools\service.pyc celeryd -f c:\logs\celery.log -l debug --settings=rcs_main.win_dev
[ERROR/Process-1] Process 'PoolWorker-1' pid:2568 exited with exitcode 1
[ERROR/Process-1] Process 'PoolWorker-2' pid:2196 exited with exitcode 1
[ERROR/Process-1] Process 'PoolWorker-3' pid:708 exited with exitcode 1
[ERROR/Process-1] Process 'PoolWorker-4' pid:4016 exited with exitcode 1
[ERROR/Process-1] Process 'PoolWorker-5' pid:3828 exited with exitcode 1
[ERROR/Process-1] Process 'PoolWorker-6' pid:3416 exited with exitcode 1
[ERROR/Process-1] Process 'PoolWorker-7' pid:3228 exited with exitcode 1
[ERROR/Process-1] Process 'PoolWorker-8' pid:1348 exited with exitcode 1

**Comment by findsarfaraz** [comment]
Where is fix for this issue. I am facing the same. Please help

**Comment by timtan** [comment]
Use the code in Github, not pypi.   Can @antoinemartin publish a new version and n pypi?

**Comment by ghjconan** [comment]
Greeting,

I am encounting this issue when testing my app. Here is my debug log. My currently understanding is something went wrong in billliard side.

(env) d:\website\<site_name>>python service.py debug
Debugging service <service_name> - press Ctrl+C to stop.
Info 0x400000FF - Initialization
Info 0x400000FF - d:\website\<site_name>\service.ini
Info 0x400000FF - starting
Info 0x400000FF - Spawned D:\website\<site_name>\env\lib\site-packages\django_windows_tools\servi
ce.pyc celery worker -A <project_name> -l info -f d:\website\<site_name>\celeryworker1.log
Info 0x400000FF - Started. Waiting for stop
No handlers could be found for logger "multiprocessing"

 -------------- celery@GUHUAJUN v3.1.19 (Cipater)
---- **** -----
--- * ***  * -- Windows-7-6.1.7601-SP1
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         <project_name>:0x30a18d0
- ** ---------- .> transport:   redis://127.0.0.1:6379/0
- ** ---------- .> results:     djcelery.backends.database:DatabaseBackend
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . api.tasks.add_downloadjob
  . api.tasks.check_file
  . api.tasks.remove_olditems
  . <project_name>.celery.debug_task

Info 0x400000FF - Started. Waiting for stop
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\website\<site_name>\env\lib\site-packages\billiard\forking.py", line 430, in main
    prepare(preparation_data)
  File "D:\website\<site_name>\env\lib\site-packages\billiard\forking.py", line 557, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named PythonService
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\website\<site_name>\env\lib\site-packages\billiard\forking.py", line 430, in main
    prepare(preparation_data)
  File "D:\website\<site_name>\env\lib\site-packages\billiard\forking.py", line 557, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named PythonService

**Comment by mrbean-bremen** [comment]
@antoinemartin - if you can find the time, could you push the current version to pypi?
There are a number of fixes in since last push, and this make the live easier for the users...
I already increased the version to 0.1.2, but only the original owner is allowed to push to pypi.

Thanks in advance!

**Comment by antoinemartin** [comment]
Done. If you give me a valid pypi username, I'd be more than happy to hand over the ownership to you.

**Comment by mrbean-bremen** [comment]
Thanks a lot! My pypi username is the same as on github, if you really want to transfer the ownership, though I think it's not really needed.

**Comment by antoinemartin** [comment]
Done. We are now owners together of the project on pypi. As I already said before, I'm sorry if I can't handle update requests but I made this package in 2012 for a client that wanted to run all its servers on Windows. 

I thought at the time that running Django on Windows was a bad idea. It's even more the case now that alternatives like Docker exists.

**Comment by mrbean-bremen** [comment]
Thank you - I didn't realize that shared ownership is possible on pypi. And I completely agree about running django servers on Windows. But that's the thing with big companies - they move very slowly, and it will take some time before they get to use other technologies than what they are used to. Anyway, if you have to go this path, it is nice to have helper tools like this one, as configuration in Windows can be a nightmare. So thank you for that!

**Comment by mrbean-bremen** [comment]
Closing this as fixed in the latest pypi version, as far as I can see.
